### ISSUE TITLE
[Hacktoberfest] Add golint plugin

### ISSUE THREAD

**Issue by eddycharly** [jenkins-x/lighthouse#1011]
This issue tracks the addition of the [golint](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/golint) plugin to Lighthouse.

A quick guide about porting a Prow plugin to Lighthouse is available [here](https://github.com/jenkins-x/lighthouse#porting-prow-commands)

This issue should be a good candidate for newcomers that want to contribute to the project.

**Comment by abayer** [comment]
This one might be a little tough because the `golint` plugin is heavily dependent on implementation details of GitHub's reviews API to do line-by-line comments. I took a quick look at it a month or two ago and decided it wasn't a one or two day task to actually work right on GitLab (and I ignored BitBucket Server completely).

**Comment by eddycharly** [comment]
Yeah, but hacktoberfest is one month long... maybe someone wants to battle with it like crazy 😛
We can add a bit of warning in the description too !

**Comment by eddycharly** [comment]
One option I’m considering too is to allow plugins to declare the scm providers they support.
This would allow for the golint plugin to be github specific.
