### ISSUE TITLE
jx does not support gitlab v4 REST API

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/lighthouse#332]
so we should maybe look at using creating a gitProvider in `jx` using go-scm which already supports gitlab v4.

If this works we could then consider switching folks over to a go-scm based implementation of the `jx` `pkg/gits` providers to simplify the codebase and trim the dependences in jx

**Comment by TonyNoble** [comment]
Minor note - jx has been updated (as of December, IIRC) to use the latest version of its gitlab provider, which does support V4 API.  There are still some bits that attempt to use v3, but that's largely because they're not differentiating between GitLab and GitHub, rather than incorrect API usage.

That's not to say that it wouldn't still make sense to unify which library is being used, of course.
