### ISSUE TITLE
migration from prow - unknown plugins: blunderbuss, heart and config-updater

### ISSUE THREAD

**Issue by masseybradley** [jenkins-x/lighthouse#577]
### Summary 

`lighthouse` logs warnings related to unknown plugins after `jx boot` migrating from `prow`:
```
{"level":"warning","msg":"unknown plugin","plugin":"config-updater","time":"2020-03-05T12:18:40Z"}
{"level":"warning","msg":"unknown plugin","plugin":"blunderbuss","time":"2020-03-05T12:18:40Z"}
{"level":"warning","msg":"unknown plugin","plugin":"heart","time":"2020-03-05T12:18:40Z"}
```

### Steps to reproduce the behavior

Migrate from `prow` to `lighthouse`.

### Expected behavior

Support for existing / default plugins.

### Actual behavior

Warnings related to unknown plugins.

### Jx version

The output of `jx version` is:

```
jx                 2.0.1231
Kubernetes cluster v1.15.7-gke.23
kubectl            v1.17.3
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```
Lighthouse version: `0.0.389`

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Lighthouse)
- [ ] Classic Jenkins

**Comment by abayer** [comment]
So `config-updater` is one we should remove from Jenkins X's default `plugins.yaml` setup in the first place, because we manage the `config.yaml` and `plugins.yaml` through Jenkins X in general. 

`blunderbuss`, which is what automatically adds reviewers to a new PR from users in the `OWNERS` file, hasn't been ported over to Lighthouse, but we could definitely do so. Same is true for `heart`, which adds emoji reactions to comments containing a string matching a configured regexp or to PRs that add people to the `OWNERS` file.

So the message that shows up here is just noise - in practice, we probably should migrate `blunderbuss` and `heart` over to Lighthouse and remove `config-updater` from the Jenkins X logic that generates the `plugins.yaml` in the first place.

Also, fwiw, `/cat` isn't the command, `/meow` is. =)
