### ISSUE TITLE
BDD/E2E tests for ChatOps

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/lighthouse#64]
our current [BDD tests](https://github.com/jenkins-x/bdd-jx) test that we can create projects, promote them and create PRs against them and have previews created via the different git providers.

However we've no BDD tests that verify the various ChatOps commands like `/lgtm /approve /test all` and the like work on the different git providers.

We should add some BDD tests for those things on the created PR in the BDD test

**Comment by ccojocar** [comment]
I think that we can add some E2E test in Lighthouse to test this feature in isolations since they are strictly related to the git providers and not jenkins-x.

**Comment by wbrefvem** [comment]
It appears that on the Vault cluster, the the git auth is coming back empty. This is the first time we've used git providers in the BDD tests, and since the tests for the approve plugin are passing on the other clusters, my suspicion is that there's a bug somewhere in how git auth is configured under Vault. Each cluster is setup with `jx step bdd`, which wraps `jx boot`, so they should work identically assuming the git auth credentials are set up correctly. My next step is to investigate how `jx step bdd` sets up the Vault credentials.

**Comment by ccojocar** [comment]
@warrenbailey This is a known issue which I am currently working on.  The git auth is not set up in vault at the end of boot installation. See #https://github.com/jenkins-x/jx/issues/5114 and https://github.com/jenkins-x/jx/issues/6036.

**Comment by abayer** [comment]
Closing.
